pandoc assets/test-1.md \
    -o build-1.pdf \
    --from markdown \
    --template eisvogel.latex \
    --shift-heading-level-by=-1 \
    --resource-path=assets \
    --number-sections \
    --highlight-style monochrome \
    --top-level-division=chapter \
    --pdf-engine "xelatex" \
    --toc \
    -V CJKmainfont="Noto Serif CJK SC" \
    -V toc-own-page="true" \
    -V book \
    -V titlepage="true" \
    -V titlepage-color="FFFFFF" \
    -V code-block-font-size="\normalsize" \
    -V titlepage-rule-height="0"
