name: Simple Usage

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: pandoc -s assets/test-1.md -o test-1.html # gets appended to pandoc command
