name: Simple Usage

on:
  workflow_dispatch:
  push:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # access repo files
      - run: stamp=$(date +"%Y-%m-%d.H:%M:%S")
      - uses: docker://pandoc/core:2.9
        with:
          args: pandoc -d PandocDefaults.yml -o artifact/build-${{ github.run_id }}.html
      - name: push new file
        run: |
          git config user.name TieWay59
          git config user.email tieway59@foxmail.com
          git add .
          git commit -m "generated"
          git push
