name: build code book

on:
  workflow_dispatch:
  push:

jobs:
  convert:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # access repo files

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H:%M:%S')"

      - name: PandocLatex
        uses: ./
        with:
          args: >-
            pandoc assets/test-1.md 
            -o artifact/build.pdf
            --from markdown 
            --template eisvogel.latex 
            --resource-path=assets 
            --number-sections 
            --top-level-division=chapter 
            --shift-heading-level-by=-1 
            --highlight-style monochrome 
            --pdf-engine "xelatex" 
            --toc 
            -V CJKmainfont="Noto Serif CJK SC" 
            -V toc-own-page="true" 
            -V book
            -V code-block-font-size="\normalsize"
            -V title="代码模板"
            -V author="Tieway59"
            -V date="${{ steps.date.outputs.date }}"

      - name: UploadArtifact
        uses: actions/upload-artifact@master
        with:
          name: build-${{ github.run_number }}
          path: artifact

      - name: PushCommit
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          cp artifact/build.pdf backups/build_${{ steps.date.outputs.date }}.pdf
          git config user.name TieWay59
          git config user.email tieway59@foxmail.com
          git add .
          git commit -m "CI: produce build-${{ steps.date.outputs.date }}.pdf"
          git push

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/build.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
