name: build code book

on:
  workflow_dispatch:
  push:

jobs:
  convert:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # access repo files

      - name: PandocLatex
        uses: ./
        with:
          args: >-
            pandoc assets/test-1.md 
              -o artifact/build.pdf
              --from markdown 
              --template eisvogel.latex 
              --resource-path=assets 
              --number-sections 
              --top-level-division=chapter 
              --shift-heading-level-by=-1 
              --highlight-style monochrome 
              --pdf-engine "xelatex" 
              --toc 
              -V CJKmainfont="Noto Serif CJK SC" 
              -V toc-own-page="true" 
              -V book
              -V code-block-font-size="\normalsize"
              -V title="代码模板"
              -V author="Tieway59"
              -V date="2017-02-20"

      - name: UploadArtifact
        uses: actions/upload-artifact@master
        with:
          name: build-${{ github.run_number }}
          path: artifact

      - name: PushCommit
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          cp artifact/build.pdf backups/build-${{ github.run_number }}.pdf
          git config user.name TieWay59
          git config user.email tieway59@foxmail.com
          git add .
          git commit -m "CI: produce build-${{ github.run_number }}.pdf"
          git push
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/build.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
