name: Simple Usage

on:
  workflow_dispatch:
  push:

jobs: # ${{steps.date.outputs.date}}
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # access repo files

      - name: Pandoc
        uses: ./
        with:
          args: >-
              pandoc assets/test-1.md 
              -o build-1.pdf 
              --from markdown 
              --template eisvogel.latex 
              --shift-heading-level-by=-1 
              --resource-path=assets 
              --number-sections 
              --highlight-style monochrome 
              --top-level-division=chapter 
              --pdf-engine "xelatex" 
              --toc 
              -V CJKmainfont="Noto Serif CJK SC" 
              -V toc-own-page="true" 
              -V book 
              -V titlepage="true" 
              -V titlepage-color="FFFFFF" 
              -V code-block-font-size="\normalsize" 
              -V titlepage-rule-height="0"

# -d PandocDefaults.yml -o artifact/build-${{ github.run_number }}.pdf --template eisvogel --number-sections

      - name: UploadArtifact
        uses: actions/upload-artifact@master
        with:
          name: build-${{ github.run_number }}
          path: artifact

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/build-${{ github.run_number }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PushCommit
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          git config user.name TieWay59
          git config user.email tieway59@foxmail.com
          git add .
          git commit -m "action run_number ${{ github.run_number }}"
          git push
          
